### ISSUE TITLE
Update packages to use WithDependencies

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/widget_toolkit#107]
Currently there are several places within the `widget_toolkit` and `rx_bloc` ecosystem which use different naming approaches when it comes to widgets that also include their dependencies. The agreed approach for all widgets is to name their `WithDependencies` variants as standalone widgets, removing any factory constructors or static methods that reference widget creation with dependencies.

ACs:
- [x] Update rx_bloc ecosystem classes (where applicable)
- [x] Update widget_toolkit classes:
  - [x] widget_toolkit
- [x] Update documentation/Changelog

**Comment by JvnSlv** [comment]
Tested and it looks like the requirements are met
