### ISSUE TITLE
widget_toolkit_pin known issues

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/widget_toolkit#112]
During the testing of the `widget_toolkit_pin` package, a few different issues (visual and functional) were noticed by @JvnSlv . Below you can find a list of them along with screenshots and details on those bugs.

> [!NOTE]
> Not all of those issues can be reproduced in the current version of the example project.

---

<details>
 <br/>
  <summary>1. Buttons remain visually held even after letting go of them. </summary>
 <br/>

Upon releasing a previously held button, the button remains visually held even though it isn't anymore. In order to cancel out the visual bug, one must press the button again (without holding it).

 ![Screenshot_1721739456](https://github.com/user-attachments/assets/a3083631-cdfa-4097-9578-cd9770876fb6)

</details>

<details>
 <br/>
  <summary>2. Error if device biometrics (pin,fingerprint,etc) is not set</summary>
 <br/>

Upon successfully entering the pin (`1111`), the biometrics button appears. On Android, upon pressing the biometrics button, if the device biometrics isn't configured (fingerprint, for example) an unhandled error will be presented.

![Screenshot_1721739245](https://github.com/user-attachments/assets/257eb175-51a3-40ae-9810-d50b6c00f659)

</details>

<details>
 <br/>
  <summary>3. Dots are hidden during quick re-entry after incorrect pin </summary>
 <br/>

If the user tries to enter a new pin quickly when the error message is presented after an incorrect pin, the dots indicating the number of entered digits won't be present. This issue can be manually fixed if the user taps on any of the buttons (either by adding a new digit or by pressing the delete/backspace button).

In the image below, three digits are entered (and the delete/backspace button is enabled) but the dots representing those digits are absent.

![Screenshot_1721739981](https://github.com/user-attachments/assets/cf6d068e-f873-403d-bead-81986d36b839)

</details>

<details>
 <br/>
  <summary>4. Pin code not registered if entered too fast</summary>
 <br/>

This issue may not be present in the current version of the package/example. It is listed here from its [original ticket](https://github.com/orgs/Prime-Holding/projects/3/views/1?pane=issue&itemId=40949170). Not much info about this issue is known.

</details>

<details>
 <br/>
  <summary>5. Biometrics button disappears when the user starts typing PIN code</summary>
 <br/>

This issue may not be present in the current version of the package/example. It is listed here from its [original ticket](https://github.com/orgs/Prime-Holding/projects/3/views/1?pane=issue&itemId=40793172). Not much info about this issue is known, except from its title.

</details>

**Comment by DDavidPrime** [comment]
Estimate: 16h

**Comment by StanevPrime** [comment]
@DDavidPrime please release this bug-fix.
