### ISSUE TITLE
Loading Indicator Misalignment in SmallButton Widget

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/widget_toolkit#114]
When the SmallButton widget's state is set to ButtonStateModel.loading, the loading indicator is aligned to the right margin. The expected behavior is for the loading indicator to be centered within the button.

Steps to Reproduce:
1. Set the SmallButton widget to ButtonStateModel.loading.
2. Observe the position of the loading indicator.

Expected Behavior:
The loading indicator should be centered within the button when the button is in the ButtonStateModel.loading state.

Actual Behavior:
The loading indicator is aligned to the right margin when the button is in the ButtonStateModel.loading state.

AC:
- [ ] The loading indicator should be centered within the SmallButton when in the ButtonStateModel.loading state.
- [ ]  Appropriate padding should be added to ensure visual consistency and spacing around the loading indicator.

![Screenshot_1721916209](https://github.com/user-attachments/assets/2c6f680e-ae7d-4295-bc9b-f7faa03928d3)
![Screenshot_1721916212](https://github.com/user-attachments/assets/18abe583-dc9f-4a9b-9cb1-70c44e2af311)

**Comment by DDavidPrime** [comment]
Tested and the issue should be fixed now. 👍
