### ISSUE TITLE
Widget_toolkit_qr failing CI

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/widget_toolkit#120]
The CI/CD pipeline has reported the following issue during the analysis step:
```
Run flutter analyze lib
  flutter analyze lib
  shell: /usr/bin/bash -e {0}
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/3.24.0-stable/x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/3.24.0-stable/x64/.pub-cache
Analyzing lib...                                                

   info • Don't use 'BuildContext's across async gaps • lib/src/lib_qr_scanner/views/qr_scanner_component.dart:176:22 • use_build_context_synchronously

1 issue found. (ran in 10.3s)
Error: Process completed with exit code 1.
```

## Steps to Reproduce:
    Run `flutter analyze lib` in `widget_toolkit_qr`
    
## Problem:
The use_build_context_synchronously warning is triggered when a BuildContext is used after an asynchronous gap (e.g., after an await statement), which can lead to unexpected behavior if the BuildContext is no longer valid.

## Proposed Solution:
Refactor the code at the reported line to ensure that the BuildContext is used synchronously or passed in a way that prevents this warning. One approach could be checking if the widget is still mounted before using the BuildContext or restructuring the logic to avoid asynchronous gaps.

**Comment by DDavidPrime** [comment]
With the PR #124 merged, this should be addressed. Reopen if otherwise.
