### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by azazadev** [Prime-Holding/widget_toolkit#122]
Could you please upgrade the **widget_toolkit** and **local_auth** dependencies in **widget_toolkit_biometrics** and **widget_toolkit_pin** to the latest versions?

**Comment by DDavidPrime** [comment]
There were a lot of changes (and blockers) in the works regarding the updated version of the packages. But since they are now out, I'm closing this ticket. If any other issues occur, please open a separate ticket.
