### ISSUE TITLE
Refactor widget_toolkit_pin package

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/widget_toolkit#130]
With the latest changes, the widget_toolkit_pin works as expected. However, there are some visual discrepancies when it comes to entering inputs quickly.

A common case where this discrepancy happens is when the user quickly types a wrong pin code, resulting in an error. If the user continues entering new digits before the error is displayed, those will be registered. When the error is displayed, those will be temporarily hidden from the UI. Once the error starts fading out, the previous state won't be restored and nothing will be displayed in the UI. If the user enters another input, only then will the new state show up on the screen. Any input entered after the error message is shown will be registered.

Due to the current implementation of the widget_toolkit_pin there are some limitations which prevent us in addressing this issue in a straightforward way. One way to address that issue is by refactoring the existing code, allowing for a cleaner implementation.

ACs:
- [x] Investigate & change pinLength & error animation behavior

Estimate: 1d

**Comment by DDavidPrime** [comment]
@DDavidPrime Provide ACs for widget_toolkit_pin with estimations.

**Comment by GoranPrime** [comment]
Blocks: https://github.com/Prime-Holding/rx_bloc/issues/721
