### ISSUE TITLE
Fix widget_toolkit_pin pub.dev score

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/widget_toolkit#145]
The pub.dev score of the `widge_toolkit_pin` package is currently 150 but should ideally be 160. Upon investigation, it was identified that the score deduction is caused by the use of the deprecated `color.withOpacity()` method in the codebase.

AC's

- [x] Replace all instances of `color.withOpacity()` with the recommended alternative approach using `color.withValues()`
- [x] Update example project

**Comment by DDavidPrime** [comment]
Tested and confirmed with flutter version `3.27.1` on Android and iOS.
