### ISSUE TITLE
Improve pub.dev scores for widget_toolkit and widget_toolkit_otp packages

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/widget_toolkit#146]
The current pub.dev scores for the following packages are:

widget_toolkit: 150

widget_toolkit_otp: 140

Ideally, both scores should be 160. Upon investigation, it was identified that the score deduction for widget_toolkit and widget_toolkit_otp is caused by the use of the deprecated color.withOpacity() method in the codebase.

AC's

- [x] Replace `color.withOpacity()` with `color.withValues()` in the widget_toolkit
- [x] Replace `color.withOpacity()` with `color.withValues()` in the widget_toolkit_otp
- [ ] Make sure that the example applications run without issues

**Comment by DDavidPrime** [comment]
Tested and confirmed on Android and iOS with flutter version `3.27.1`
