### ISSUE TITLE
Implement the example project as part of the widget_toolkit

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/widget_toolkit#2]
It's a requirement each published package to provide an example project, which demonstrate the capabilities of the package itself. 

ACs

- Each widget should be added to a Page of a PageView
  - [x] Item picker (single and multi select)
  - [x] Search picker
  - [x] Text field dialog
  - [x] Common components
    - [x]  URL Launcher
    - [x] Shimmer
    - [x] Error bottom sheet
    - [x] Buttons
  - [x] UX Improvements
- The example should be built in a way that later could be turned to a brick of the rx_bloc_cli 

References:
- https://dart.dev/tools/pub/package-layout#examples
- https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/example/lib/main.dart

**Comment by RomanovaPrime** [comment]
[#11](https://github.com/Prime-Holding/widget_toolkit/pull/11)
