### ISSUE TITLE
[Breaking change] Edit address API improvements

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/widget_toolkit#9]
As a developer I want to have an ease to use API of the EditAddressWidget so that I can integrate that component with a minimal effort.

ACs

- [x] All icons to be moved from the widget constructor to the theme extension
- [x] Error mappers to be grouped in one abstract class
- [x] All business logic to be consolidated in one service
- [ ] Update the documentation 
  - [ ] Add an example with the minimal configuration
  - [ ] Add an example with the full configuration
- [ ] Update the package version as well as the CHANGELOG
- [ ] Add golden tests for the not-empty cases
- [x] Add Edit address in the example project
- [x] Add onChanged function receiving the changed address

**Current API**
```dart
EditAddressWidget({
    required this.cityErrorMapper,
    required this.addressErrorMapper,
    required this.validator,
    required this.searchCountryService,
    this.editAddressService = const _DefaultEditAddressService(),
    this.addressModel = _defaultAddressModel,
    this.editAddressLocalizedStrings,
    this.type = UserProfileCardTypes.mailingAddress,
    this.configuration = const EditAddressConfiguration(),
    this.countryCustomIcon,
    this.editCountryFieldType = EditFieldType.dropdown,
    this.cityCustomIcon,
    this.editCityFieldType = EditFieldType.editfield,
    this.addressCustomIcon,
    this.editAddressFieldType = EditFieldType.editfield,
    this.editContactAddressErrorBuilder,
    this.searchCountryCustomBuilders,
    Key? key,
  })
```

**Improved API**
`edit_address_widget.dart`
```dart
EditAddressWidget({
    required this.translateError,
    required this.service,
    this.onChanged, // Function (AddressModel?)
    this.initialAddress
    this.searchCountryBuilders,
    this.editContactAddressErrorBuilder,
    this.localizedStrings,
    this.configuration = const EditAddressConfiguration(),
    Key? key,
  })
```

`edit_address_service.dart`
```dart
abstract class EditAddressService<T> implements SearchPickerService<T>, TextFieldValidator<String> {
    Future<AddressModel> saveAddress(AddressModel addressModel);

    Future<List<T>> getCountries();

    List<T> getCountryPlaceholderList();

    // Default implementation
    Future<List<T>> filteredCountriesByName(List<T> list, String? searchParam);

    // Default implementation lengthIsNotEmpty
    Future<T> validateCityOnSubmit(String text);

    // Default implementation lengthIsNotEmpty
    Future<T> validateStreetOnSubmit(String text);
    
    // Default implementation lengthIsNotEmpty
    void validateCityOnType(String text);

    // Default implementation lengthIsNotEmpty
    void validateStreetOnType(String text);
}
```

`edit_address_theme.dart`
```dart
EditAddressTheme(
    this.countryIcon,
...
)
TextFieldDialogTheme(
    this.cityIcon,
    this.addressIcon,
)
```
Note: 
For the default implementation of the methods with this check : `lengthIsNotEmpty`
In the example project we need default implementation of the city and street error mappers to map the error to RxFieldException in order to see it on the screen, when we try to save the empty value.
Also currently there is a default implementation for the error that we see when we try to SAVE. For this method: Future<AddressModel> saveAddress(AddressModel addressModel); In the example project, we should provide implementation also for it, otherwise there will be no error on the screen as it shows now.

**Comment by StanislavPrime** [comment]
- [ ] Remove countryCustomIcon, cityCustomIcon, addressCustomIcon

**Comment by StanevPrime** [comment]
@StanislavPrime  the ACs have been changed based on the breaking changes implemented and described in this [PR](https://github.com/Prime-Holding/widget_toolkit/pull/24)
